### ISSUE TITLE
Improve BSP install docs to use Sketchbook location

### ISSUE THREAD

**Issue by danielcompton** [adafruit/Adafruit_WICED_Arduino#56]
I was confused for a while when trying to setup the BSP, as the board and sketches weren't showing up when I put them at `~/Documents/Arduino/`. After a bit of thinking and debugging, I realised that I had customised the sketchbook location in the Arduino preferences. It could be good to mention that in the BSP install docs.

**Comment by microbuilder** [comment]
We're working on a new 0.6.0 release that will reorganize the examples so that they should show up correctly in recent versions of the Arduino IDE ... sorry for the trouble, but this should be fixed in a week or two with the latest release, at which point we will update the learning guide with new (easier) installation instructions to install the library via the Arduino IDE.
